# Based on: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

name: Publish Docker image

on:
  workflow_dispatch:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: sc_tools

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

        name: Set up containerd
        uses: crazy-max/ghaction-setup-containerd@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: setup
          file: setup/docker/Dockerfile
          # push: true
          tags: ${{ env.REGISTRY }}/nmoroze/${{ env.IMAGE_NAME }}:latest
          # labels: ${{ steps.meta.outputs.labels }}
          outputs: type=oci,dest=/tmp/image.tar

      - name: Import image in containerd
        run: |
          sudo ctr i import --base-name ${{ env.REGISTRY }}/nmoroze/${{ env.IMAGE_NAME }} --digests --all-platforms /tmp/image.tar

      - name: Push image with containerd
        run: |
          sudo ctr --debug i push --user "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" ${{ env.REGISTRY }}/nmoroze/${{ env.IMAGE_NAME }}:latest

